In [6]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import linear_model

In [2]:
x = np.arange(6).reshape(3,2)
print(x)
poly = PolynomialFeatures(2)
x_poly = poly.fit_transform(x)
print(x_poly)

[[0 1]
 [2 3]
 [4 5]]
[[ 1.  0.  1.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]


In [3]:
def f(x):
    return x * np.sin(x)

In [4]:
def f(x):
    return x * x * x -3 * x + 1

In [5]:
x = np.linspace(0,10,100)
np.random.shuffle(x)
x = x.reshape(-1,1)
y = f(x)
print(x.shape)
print(x[:5])
poly = PolynomialFeatures(2).fit(x)
x_poly = poly.transform(x)
print(x_poly[:5])
x_train,x_test,y_train,y_test = train_test_split(x_poly,y,test_size=0.3,random_state=1)

# 標準化
scaler = preprocessing.StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)

model = linear_model.LinearRegression()
model.fit(x_train,y_train)
pred = model.predict(x_test)

print(model.coef_)
print(mean_squared_error(y_test,pred))
print(r2_score(y_test,pred))


(100, 1)
[[0.        ]
 [6.96969697]
 [5.85858586]
 [3.83838384]
 [5.55555556]]
[[ 1.          0.          0.        ]
 [ 1.          6.96969697 48.57667585]
 [ 1.          5.85858586 34.32302826]
 [ 1.          3.83838384 14.73319049]
 [ 1.          5.55555556 30.86419753]]
[[   0.         -193.27620554  471.3634493 ]]
290496744.31981385
-4729.393976622237
